### ISSUE TITLE
Error when attempting to scroll no results

### ISSUE THREAD

**Issue by ceuk** [salman-abedin/puri#2]
[These lines](https://github.com/salman-abedin/puri/blob/master/puri.sh#L27) could probably use a check that the number of results is > 0 or something

**Comment by salman-abedin** [comment]
I didn't think anyone would need scrolling as there is usually not that many links on a doc.
In any case, it's gonna take a little more than modifying that line, but I'll take care of it. =)

**Comment by salman-abedin** [comment]
Kindly check the new commits as I've added the scrolling support.
